# Generated by Django 4.1 on 2022-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
