# Generated by Django 4.1 on 2022-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_email_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='salary',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
