# Generated by Django 4.1 on 2022-09-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_detail_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email_validator',
        ),
    ]
