# Generated by Django 5.0 on 2023-12-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_email_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='uniqueuserid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
