# Generated by Django 5.0 on 2023-12-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_detail_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temp',
            new_name='tempuser',
        ),
    ]
