# Generated by Django 5.0 on 2024-01-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_temp_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempuser',
            name='uniqueuserid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
