# Generated by Django 4.1 on 2022-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='day',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='expenseid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='month',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_detail',
            name='year',
            field=models.CharField(default=2000, max_length=30),
            preserve_default=False,
        ),
    ]
