# Generated by Django 4.1 on 2022-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryid', models.IntegerField()),
                ('replyid', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
