# Generated by Django 5.0 on 2023-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField()),
                ('groupname', models.CharField(max_length=30)),
                ('personname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('createdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid', models.IntegerField()),
                ('groupid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('paymentmode', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('createdate', models.DateField()),
            ],
        ),
    ]
