# Generated by Django 5.0 on 2023-12-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_group',
            name='createdate',
            field=models.DateField(),
        ),
    ]
