# Generated by Django 5.0 on 2023-12-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExpenses', '0002_alter_personal_group_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_group',
            name='groupname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal_group',
            name='personname',
            field=models.CharField(max_length=100),
        ),
    ]
