# Generated by Django 5.0 on 2023-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExpenses', '0003_alter_personal_group_groupname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_group',
            name='createdbyid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
