# Generated by Django 5.0 on 2023-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExpenses', '0004_personal_group_createdbyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_group',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
