# Generated by Django 5.0 on 2023-12-24 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pod_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podid', models.IntegerField()),
                ('pod_name', models.CharField(max_length=50)),
                ('createdby', models.CharField(max_length=50)),
                ('lastmodifiedby', models.CharField(max_length=50)),
                ('lastmodifiedddate', models.DateField(default=datetime.date.today)),
                ('createddate', models.DateField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pod_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podmemberid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pod_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podmemberid', models.IntegerField()),
                ('amount', models.FloatField()),
                ('transactiondate', models.DateField()),
            ],
        ),
    ]
