# Generated by Django 5.0 on 2023-12-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='podid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
