# Generated by Django 5.0 on 2023-12-24 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0003_pod_transaction_podid_pod_transaction_podmembername'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_transaction',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
