# Generated by Django 5.0 on 2023-12-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0004_pod_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_member',
            name='useruniqueid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod_transaction',
            name='useruniqueid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
