# Generated by Django 5.0 on 2023-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0005_pod_member_useruniqueid_pod_transaction_useruniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_transaction',
            name='expensetype',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod_transaction',
            name='transactionmode',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
