# Generated by Django 5.0 on 2023-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0006_pod_transaction_expensetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_transaction',
            name='transid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
