# Generated by Django 5.0 on 2024-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pod', '0007_pod_transaction_transid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_member',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
